# Generated by Django 4.0.6 on 2022-07-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(max_length=100)),
                ('resource_link', models.CharField(max_length=500)),
                ('resource_description', models.TextField(max_length=500)),
            ],
        ),
    ]
